spring:
  datasource:
    url: jdbc:mysql://localhost/InvoiceDatabase?createDatabaseIfNotExist=true&serverTimeZone=Europe/Prague
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8080

  springdoc:
    api-docs.path: /api-docs

  #puvodni nastaveni zakomentovano
  #jpa:
  #  open-in-view: true
  #  hibernate:
  #    ddl-auto: update
  #  show-sql: true

  #nastaveni pro vyvoj
  jpa: # <-- TENTO BLOK JE NYNÍ SPRÁVNĚ ODSADEN POD 'spring:'
    open-in-view: true
    hibernate:
      ddl-auto: create-drop # Toto zajistí, že se databáze smaže a znovu vytvoří
    show-sql: true # PONECHÁNO - zobrazí SQL dotazy
    defer-datasource-initialization: true # Odloží spuštění data.sql po JPA inicializaci
    properties: # NOVÉ - detailní Hibernate logování
      hibernate:
        format_sql: true # NOVÉ - naformátuje SQL dotazy
        use_sql_comments: true # NOVÉ - přidá komentáře do SQL
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # NOVÉ - zobrazí hodnoty parametrů

  sql: # <-- TENTO BLOK JE NYNÍ SPRÁVNĚ ODSADEN POD 'spring:'
    init:
      mode: always # Zajistí, že data.sql se spustí vždy
      enabled: true # Explicitně povolí spouštění SQL skriptů

  jackson: # <-- TENTO BLOK JE NYNÍ SPRÁVNĚ ODSADEN POD 'spring:'
    mapper:
      accept-case-insensitive-enums: true

# NOVÉ - Logging konfigurace pro debugging
logging:
  level:
    org.hibernate.SQL: DEBUG # NOVÉ - SQL dotazy
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # NOVÉ - parametry dotazů
    org.springframework.orm.jpa: DEBUG # NOVÉ - JPA operace
    org.springframework.jdbc.core: DEBUG # NOVÉ - JDBC operace
    org.springframework.transaction: DEBUG # NOVÉ - transakce
    cz.itnetwork: DEBUG # NOVÉ - vaše aplikace (upravte podle vašeho package)